# Use the official OpenJDK 17 image as base
FROM openjdk:17

# Set the working directory in the container
WORKDIR /app

# Copy the compiled JAR file into the container
COPY target/*.jar app.jar

# Expose the port
EXPOSE 8091

# Command to run the application
CMD ["java", "-jar", "app.jar"]
